"""update models

Revision ID: a6081ebf7b2a
Revises: 1db4146e6ad4
Create Date: 2021-01-13 09:53:03.126929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6081ebf7b2a'
down_revision = '1db4146e6ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_catalogs', sa.Column('book_id', sa.Integer(), nullable=False))
    op.alter_column('book_catalogs', 'title',
               existing_type=mysql.VARCHAR(length=255),
               comment='标题',
               existing_nullable=False)
    op.add_column('book_images', sa.Column('book_id', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('user_id', sa.Integer(), nullable=False, comment='用户id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'user_id')
    op.drop_column('book_images', 'book_id')
    op.alter_column('book_catalogs', 'title',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='标题',
               existing_nullable=False)
    op.drop_column('book_catalogs', 'book_id')
    # ### end Alembic commands ###
