"""init models

Revision ID: e8f6bf13cb07
Revises: 
Create Date: 2021-01-12 15:29:27.200332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8f6bf13cb07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False, comment='用户名'),
    sa.Column('nickname', sa.String(length=255), nullable=False, comment='昵称'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='密码'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_create_time'), 'users', ['create_time'], unique=False)
    op.create_index(op.f('ix_users_update_time'), 'users', ['update_time'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='书名'),
    sa.Column('access', sa.Integer(), nullable=False, comment='允许访问'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态'),
    sa.Column('brief', sa.Text(), nullable=False, comment='摘要'),
    sa.Column('select_catalog', sa.Integer(), nullable=False, comment='选择目录'),
    sa.Column('publish_timestamp', sa.DateTime(), nullable=False, comment='发布时间'),
    sa.Column('cover', sa.String(length=255), nullable=False, comment='封面'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联用户id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_access'), 'books', ['access'], unique=False)
    op.create_index(op.f('ix_books_create_time'), 'books', ['create_time'], unique=False)
    op.create_index(op.f('ix_books_name'), 'books', ['name'], unique=False)
    op.create_index(op.f('ix_books_publish_timestamp'), 'books', ['publish_timestamp'], unique=False)
    op.create_index(op.f('ix_books_status'), 'books', ['status'], unique=False)
    op.create_index(op.f('ix_books_update_time'), 'books', ['update_time'], unique=False)
    op.create_table('book_catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('markdown', mysql.LONGTEXT(), nullable=False),
    sa.Column('html', mysql.LONGTEXT(), nullable=False),
    sa.Column('publish_markdown', mysql.LONGTEXT(), nullable=False),
    sa.Column('publish_html', mysql.LONGTEXT(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('abstract', sa.String(length=255), nullable=True),
    sa.Column('publish_order', sa.Integer(), nullable=True),
    sa.Column('pos', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('is_dir', sa.Boolean(), nullable=False),
    sa.Column('publish_timestamp', sa.DateTime(), nullable=False),
    sa.Column('first_publish', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_catalogs_create_time'), 'book_catalogs', ['create_time'], unique=False)
    op.create_index(op.f('ix_book_catalogs_first_publish'), 'book_catalogs', ['first_publish'], unique=False)
    op.create_index(op.f('ix_book_catalogs_is_dir'), 'book_catalogs', ['is_dir'], unique=False)
    op.create_index(op.f('ix_book_catalogs_parent_id'), 'book_catalogs', ['parent_id'], unique=False)
    op.create_index(op.f('ix_book_catalogs_pos'), 'book_catalogs', ['pos'], unique=False)
    op.create_index(op.f('ix_book_catalogs_publish_order'), 'book_catalogs', ['publish_order'], unique=False)
    op.create_index(op.f('ix_book_catalogs_publish_timestamp'), 'book_catalogs', ['publish_timestamp'], unique=False)
    op.create_index(op.f('ix_book_catalogs_status'), 'book_catalogs', ['status'], unique=False)
    op.create_index(op.f('ix_book_catalogs_title'), 'book_catalogs', ['title'], unique=False)
    op.create_index(op.f('ix_book_catalogs_update_time'), 'book_catalogs', ['update_time'], unique=False)
    op.create_table('book_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_images_create_time'), 'book_images', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_images_create_time'), table_name='book_images')
    op.drop_table('book_images')
    op.drop_index(op.f('ix_book_catalogs_update_time'), table_name='book_catalogs')
    op.drop_index(op.f('ix_book_catalogs_title'), table_name='book_catalogs')
    op.drop_index(op.f('ix_book_catalogs_status'), table_name='book_catalogs')
    op.drop_index(op.f('ix_book_catalogs_publish_timestamp'), table_name='book_catalogs')
    op.drop_index(op.f('ix_book_catalogs_publish_order'), table_name='book_catalogs')
    op.drop_index(op.f('ix_book_catalogs_pos'), table_name='book_catalogs')
    op.drop_index(op.f('ix_book_catalogs_parent_id'), table_name='book_catalogs')
    op.drop_index(op.f('ix_book_catalogs_is_dir'), table_name='book_catalogs')
    op.drop_index(op.f('ix_book_catalogs_first_publish'), table_name='book_catalogs')
    op.drop_index(op.f('ix_book_catalogs_create_time'), table_name='book_catalogs')
    op.drop_table('book_catalogs')
    op.drop_index(op.f('ix_books_update_time'), table_name='books')
    op.drop_index(op.f('ix_books_status'), table_name='books')
    op.drop_index(op.f('ix_books_publish_timestamp'), table_name='books')
    op.drop_index(op.f('ix_books_name'), table_name='books')
    op.drop_index(op.f('ix_books_create_time'), table_name='books')
    op.drop_index(op.f('ix_books_access'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_update_time'), table_name='users')
    op.drop_index(op.f('ix_users_create_time'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
